## Data Analysis 
+ Till now we have seen about the basic and some advance python concept so from here we will be going to lookinto how we do the data analysis with the help of python.
+ To go forward in this path we need some knowledge about some library which will help us to make our task easy and helpfull here is the list of lib we were gonna use which includes
    + Numpy
    + Pandas
    + Matplotlib
    + Seaborn



## **Numpy**
NumPy is a fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

### How it helps us
NumPy helps to perform a wide variety of mathematical operations on arrays. It adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

### Use case
NumPy is used for:
- Performing mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

### Some functions
- `numpy.array()`: Creates an array.
- `numpy.zeros()`: Creates an array of zeros.
- `numpy.ones()`: Creates an array of ones.
- `numpy.arange()`: Creates an array with a range of values.
- `numpy.linspace()`: Creates an array with values spaced linearly in a specified interval.
- `numpy.random.rand()`: Creates an array with random values.

### Installation 
Run this command into your powershell where the pip is insatlled.

```bash
pip install numpy
```

In [2]:
# importing numpy as np 

import numpy as np


In [4]:
# lets see how the array is created with the help of numpy
arr1 = np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1)

# how to see what is the shape of array it can be 1D, 2D or multidimensional array 
#here out array is 1D array so we use shape 

print(arr1.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
(6,)


In [5]:
# we can also reshape the 1D array into the 2D or differnet dimensional array
arr2 = arr1.reshape(1,6) # here the parameter states it will be reshape to 1 row and 6 column so reshape will take (row,column) and if you dont give the proper column number it will be giving array as if we have give (1,4) it will give error as the column will be 4 but we are left with 2 more element to allot
#arr2 = arr1.reshape(1,4) # this will give error
print(arr2.shape)
print(arr2)


(1, 6)
[[1 2 3 4 5 6]]


In [8]:
# we can also create a array of shape 2D directly as well 
arr2 = np.array(([1,2,3,4,5],[2,3,4,5,6]))
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
## lets see some inbuilt function which we can use to transform the array 
### arrange function 

# The arange function in NumPy is used to create an array with evenly spaced values within a given interval. It is similar to the built-in Python range function but returns a NumPy array instead of a list.

print(np.arange(10))
print(np.arange(1,10,3).reshape(3,1))

[0 1 2 3 4 5 6 7 8 9]
[[1]
 [4]
 [7]]


In [16]:
# ones function it is used to create a array with all the ones in the array 
print(np.ones((3,4)))
print(np.ones(3))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1.]


In [19]:
# then we have identity matrix function 
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
## some more function with we can use it to get info about the array
arr = np.arange(1,10).reshape(1,9)

print(arr)
# this will give shape of array
print(arr.shape)

#this will give the number of element an array have 
print(arr.size)

# this will give the data type of the array it have 
print(arr.dtype)

#this will provide the item size in form of bytes
print(arr.itemsize)

#this will give the number of dimension the data have
print(arr.ndim)

[[1 2 3 4 5 6 7 8 9]]
(1, 9)
9
int64
8
2


#### **Numpy vectorized operation**


In [22]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9,10])

# addition on the two array
print('Addition of 2 array',arr1+arr2)

# subtraction on two array
print('Subtraction of 2 array',arr1-arr2)

#Multiplication 
print('Multiplication of 2 array',arr1*arr2)

# Division
print('Division of 2 array',arr1/arr2)

Addition of 2 array [ 6  8 10 12 14 16]
Subtraction of 2 array [-4 -4 -4 -4 -4 -4]
Multiplication of 2 array [ 5 12 21 32 45 60]
Division of 2 array [0.2        0.33333333 0.42857143 0.5        0.55555556 0.6       ]


In [24]:
## lets see some universal function that will apply on the whole array there are multiple functino here are some example

#square root
print(np.sqrt(arr1))

#exponential
print(np.exp(arr1))

#sine
print(np.sin(arr1))

#natural log
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


#### **Array Slicing and indexing**

In [32]:
arr = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]))
print(arr)
print(arr.shape)

# how to get one element from a 2D array for that we need to know which row and column it is in 
print(arr[0][1]) # we will give first index as [row][column] or [row,column]
print(arr[1,2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
2
8


In [30]:
# we can also slice it like a string or list 
print(arr[0:,3:])# this will give us the last two element of the every row or the element prensent in the last 2 column 

[[ 4  5]
 [ 9 10]
 [14 15]]


In [33]:
# Mean of the array
print("Mean of arr:", np.mean(arr))
print("Mean of arr1:", np.mean(arr1))

# Median of the array
print("Median of arr:", np.median(arr))
print("Median of arr1:", np.median(arr1))

# Standard deviation of the array
print("Standard deviation of arr:", np.std(arr))
print("Standard deviation of arr1:", np.std(arr1))

# Variance of the array
print("Variance of arr:", np.var(arr))
print("Variance of arr1:", np.var(arr1))

# Sum of the array
print("Sum of arr:", np.sum(arr))
print("Sum of arr1:", np.sum(arr1))

# Minimum value in the array
print("Minimum value in arr:", np.min(arr))
print("Minimum value in arr1:", np.min(arr1))

# Maximum value in the array
print("Maximum value in arr:", np.max(arr))
print("Maximum value in arr1:", np.max(arr1))

Mean of arr: 8.0
Mean of arr1: 3.5
Median of arr: 8.0
Median of arr1: 3.5
Standard deviation of arr: 4.320493798938574
Standard deviation of arr1: 1.707825127659933
Variance of arr: 18.666666666666668
Variance of arr1: 2.9166666666666665
Sum of arr: 120
Sum of arr1: 21
Minimum value in arr: 1
Minimum value in arr1: 1
Maximum value in arr: 15
Maximum value in arr1: 6


In [38]:
# logical operation on the array 
data = np.arange(1,10)

print(data[data>5])
print(data[data<2])
print(data[(data>2) & (data<9)])

[6 7 8 9]
[1]
[3 4 5 6 7 8]
